spring:
  application:
    name: smart-fitness-system-test
  
  # Use H2 in-memory database for testing
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false
  
  flyway:
    enabled: false # Disable flyway for H2 testing
  
  security:
    user:
      name: admin
      password: admin123

# JWT Configuration for testing
fitness:
  jwt:
    secret: testSecretKey12345678901234567890123456789012345678901234567890
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
  
  # OpenCV Configuration
  opencv:
    confidence-threshold: 0.7
    motion-analysis:
      min-detection-confidence: 0.5
      min-tracking-confidence: 0.5
  
  # WebSocket Configuration
  websocket:
    allowed-origins: "*"

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    com.fitness: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 